### ISSUE TITLE
🐞 Indentation issue

### ISSUE THREAD

**Issue by JGeek00** [CodeEditApp/CodeEditSourceEditor#175] opened 2023-04-08 17:58 UTC
### Description

When I'm editing a JSON file, if I hit enter to add a new line, it doesn't start the new line just below the position where I have the cursor on the current one. Instead it starts the new line like 4 spaces to the right.

### To Reproduce

See attached video

### Expected Behavior

The new line should start with the cursor on the exact same position as I left the previous line

### Version Information

CodeEdit: 0.0.3-32
macOS: 13.2.1
Xcode: N/A

### Screenshots

https://user-images.githubusercontent.com/47545344/230736086-7b88142b-88ee-4f56-b769-770c5af406d4.mp4

**Comment by telectr** [comment] 2024-01-28 22:35
I am unable to reproduce this bug on CodeEdit 0.0.3-alpha (37). Has it been fixed?

**Comment by austincondiff** [comment] 2024-01-29 06:43
You are right, it has been fixed with our recent text view replacement.

**Closed by austincondiff** 2024-01-29 06:43 UTC
Labels: bug
